### PR TITLE
Enable test components to handle props.children

### PR DESCRIPTION
**Pull request by neo**
Used in SAEI, should've make the change in the generator.

### CODE REVIEW

**Comment by namniak** [comment]
this one is already there in one of the pending PRs

**Comment by namniak** [comment]
https://github.com/Jam3/generator-jam3/pull/326/files#diff-93e76e8321c01bb9a194f4b6022469ebR18

**Comment by neo** [comment]
Good to know, thank you! @namniak 
btw what's the plan of merging all your PRs? can't wait

**Comment by neo** [comment]
Duplicate of #326.

**Pull request closed without merging**
