### PR TITLE
Remove F1, replace animations with GSAP

### PR DESCRIPTION
**Pull request by njam3**

### CODE REVIEW

**Comment by namniak** [comment]
looks good. wonder if we need https://www.npmjs.com/package/@jam3/gsap-promise instead of gsap? what do people usually use?

**Comment by njam3** [comment]
All the projects I've worked on used regular `gsap` but i do see a lot of projects using `gsap-promise` as well. I don't want to force people to use one of the other, as it really doesn't matter to me, but I do want to have a basic animation between sections setup in the generator. Does `gsap-promise` still call the `onComplete` property if passed in? If that's the case, then we might as well use it since tweens can be written either way.

**Comment by jeremenichelli** [comment]
I think the point of using a `Promise` wrapped library is to avoid callbacks like `onComplete` and use `then`, so I guess you can execute the logic there instead of a callback.

**Comment by jeremenichelli** [comment]
Oh good point @njam3, true that I would prefer devs to have both options too.

**Comment by namniak** [comment]
Hey guys, `onComplete` won't work with gsap-promise. So to do anything on complete, people need to use `then` so to be sorta familiar with promises (when they wanna use them they always have to return the promise etc). 
Maybe, actually, a good Idea is to keep it more generic and use pure `gsap` the way you have it.
Easy to swap for a couple of existing components.

**Comment by namniak** [comment]
Also there are different wersions of gsap promise, the old one when you have to cancel promises for `then` not to be called and the new one when killing tweens will cancel promises for you. So this may also confuse users.

**Pull request merged**
